title: Awesome GitHub Apps
email: joshdan65@gmail.com
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: JoshuaTheMiller
github_username:  JoshuaTheMiller
